# Generated by Django 4.0.3 on 2022-05-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
