# Generated by Django 4.0.3 on 2022-05-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250)),
                ('category', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
