# Generated by Django 4.0.3 on 2022-05-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_maincourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='maincoursedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250)),
                ('category', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=20)),
                ('descriptiondetail', models.TextField(max_length=600)),
                ('ingredient', models.TextField(max_length=150)),
            ],
        ),
    ]
