# Generated by Django 4.0.3 on 2022-05-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_sweetdb_vegetabledb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainCourse',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='maincourse', max_length=30),
        ),
    ]
